### ISSUE TITLE
Add the embedded repository to our Github Organization's profile

### ISSUE THREAD

**Issue by 448-OG** [RustaceansKenya/.github#2]
We have created a new repository for embedded Rust collaboration. We need to add as the second point in our Projects section as seen below:

Projects
1. Rustaceans Kenya Webapp
2. Embedded <- Add this

The file is located at https://github.com/RustaceansKenya/.github/tree/master/profile

**Comment by richie-omondi** [comment]
Hey @448-OG. I'd like to take on this issue.

**Comment by 448-OG** [comment]
Go ahead

**Comment by 448-OG** [comment]
This issue was closed by PR https://github.com/RustaceansKenya/.github/pull/3
